---
- name: Exécuter VSTOR + Rainbow directement depuis le réseau
  hosts: windows
  gather_facts: no

  tasks:
    # ATTENTION : Cette méthode n'est généralement PAS compatible avec les fichiers .exe
    # qui ne sont pas spécifiquement conçus pour être exécutés depuis un partage réseau.
    # La plupart des installeurs .exe nécessitent une copie locale.

    - name: Exécuter VSTOR depuis le partage réseau
      win_command: cmd /c "\\SFRtoufs01\clients\_RAINBOW\vstor_redist.exe /quiet /norestart"
      register: vstor_install
      ignore_errors: no # L'ignorer ici est risqué, mieux vaut gérer l'échec

    - name: Afficher le résultat de l'exécution VSTOR
      debug:
        var: vstor_install

    - name: Exécuter Rainbow depuis le partage réseau
      win_command: cmd /c "\\SFRtoufs01\clients\_RAINBOW\Rainbow_Installer-x64.exe /silent ALLUSERS=TRUE"
      register: rainbow_install
      ignore_errors: no # Idem, mieux vaut gérer l'échec

    - name: Afficher le résultat de l'exécution Rainbow
      debug:
        var: rainbow_install
