---
- name: Tester l'accès au dossier réseau WinRM
  hosts: windows
  gather_facts: no

  tasks:
    - name: Vérifier l'accès au partage réseau Windows
      win_stat:
        # Doubler les anti-slashes dans le chemin UNC
        path: \\\\SFRtoufs01\\clients\\_RAINBOW
      register: network_share_status

    - name: Afficher le statut de l'accès au partage réseau
      debug:
        var: network_share_status

    - name: Message de succès si le partage est accessible
      debug:
        # Doubler les anti-slashes ici aussi dans le message
        msg: "Succès : L'accès au partage réseau \\\\SFRtoufs01\\clients\\_RAINBOW est confirmé !"
      when: network_share_status.exists

    - name: Message d'échec si le partage n'est pas accessible
      debug:
        # Doubler les anti-slashes ici aussi dans le message
        msg: "Échec : L'accès au partage réseau \\\\SFRtoufs01\\clients\\_RAINBOW est refusé ou le chemin n'existe pas."
      when: not network_share_status.exists
