---
- name: Tester l'accès au dossier réseau WinRM
  hosts: windows
  gather_facts: no

  tasks:
    - name: Vérifier l'accès au partage réseau Windows
      win_stat:
        path: \\\\SFRtoufs01\\clients\\_RAINBOW # Doublé les anti-slashes comme corrigé précédemment
      register: network_share_status

    - name: Afficher le statut complet de l'accès au partage réseau (pour diagnostic)
      debug:
        var: network_share_status

    - name: Message de succès si le partage est accessible
      debug:
        msg: "Succès : L'accès au partage réseau \\\\SFRtoufs01\\clients\\_RAINBOW est confirmé !"
      # CORRECTION ICI : Accéder à network_share_status.stat.exists
      when: network_share_status.stat.exists is defined and network_share_status.stat.exists

    - name: Message d'échec si le partage n'est pas accessible
      debug:
        msg: "Échec : Le chemin réseau \\\\SFRtoufs01\\clients\\_RAINBOW n'est PAS accessible ou n'existe pas."
      # CORRECTION ICI : Accéder à network_share_status.stat.exists
      when: network_share_status.stat.exists is defined and not network_share_status.stat.exists

    - name: Message d'erreur si la vérification stat a échoué (problème de permissions profondes ou chemin invalide)
      debug:
        msg: "ERREUR : La vérification du partage réseau a échoué. Le chemin est-il correct et le compte a-t-il des droits ? {{ network_share_status.msg | default('N/A') }}"
      when: network_share_status.failed is defined and network_share_status.failed
