---
- name: Effectuer les mises à jour Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Rechercher et installer les mises à jour Windows (sans redémarrage)
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: no

